name: Validate

on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: self-hosted
    name: Test (Go ${{ matrix.go-version }})
    container:
      image: node:20-bookworm

    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.26.4"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...
